### PR TITLE
Fix toPrintable removing ascii spaces which are printable.

### PR DESCRIPTION
**Pull request by HemilTheRebel**
Space is a printable character. Scram is a dependency pgjdbc uses to implement scram authentication. Pgjdbc normalizes string using this StringPreparations.NO_PREPARATION by default. This causes spaces in passwords to be stripped causing authentication failures due to wrong hash. [RFC 4013](https://tools.ietf.org/html/rfc4013) does not prohibit ASCII spaces.

### CODE REVIEW

**Comment by davecramer** [comment]
@ahachete can you have a look at this ?

**Comment by HemilTheRebel** [comment]
Any updates?

**Comment by davecramer** [comment]
I'm pretty sure it's just taking some time.

**Comment by HemilTheRebel** [comment]
Yeah. I am sorry.

**Comment by ahachete** [comment]
Hi @HemilTheRebel 

I agree conceptually with the change. SASLPrep consider the printable ASCII space (U0020) as a valid character (despite StringPrep recommendation that it shouldn't be). So the change is OK.

However, it doesn't pass the tests. There are some tests that fail, like `doNormalizeNoPreparationEmptyAfterNormalization(com.ongres.scram.common.stringprep.StringPreparationTest)`. They'd also need to be adjusted accordingly.

Could you please fix the tests to and submit a rebased PR including the original change and fixed tests?

**Comment by HemilTheRebel** [comment]
Oh. I didnt realise the tests were failing. I will submit the patch in a
few hours.

Thanks

**Comment by HemilTheRebel** [comment]
Have a look now @ahachete . I wanted to ask are there any other projects that are using this library that might break because of this change?

**Comment by ahachete** [comment]
Code looks good to me @HemilTheRebel . But may you please:
* Squash both commits into a single one (git rebase && git push -f to the branch)
* Use git commit -s to sign your commit marking acceptance of the [DCO](https://developercertificate.org/).

Thank you.

**Comment by ahachete** [comment]
Most if not all of the projects using this library seem to use it as a transitive dependency from pgjdbc. I hope this change won't break any of them, but honestly there's no way for me to know. If this would be the case, I expect an issue to be raised.

**Comment by HemilTheRebel** [comment]
In that case i will, squash them. Thanks for helping me out. Means a lot to
me 😀

**Comment by HemilTheRebel** [comment]
Rebase is creating a third commit containing both changes. I tried to force rebase but it is still giving me the same result. Can I get away with 2 commits?

**Comment by davecramer** [comment]
@ahachete any issues pushing this in?

**Comment by jorsol** [comment]
@HemilTheRebel could you please open this Merge Request on this repository?: https://gitlab.com/ongresinc/scram/

**Comment by HemilTheRebel** [comment]
@jorsol I am confuded now. This was a Pull Request itself on the said repository?

**Comment by jorsol** [comment]
@HemilTheRebel the primary repository is now at GitLab, and this repository is now a mirror, so if you like, you can open a Merge request (Pull request) on GL, or I could probably add the changes myself later.

Anyway, the issue you had in the PostgreSQL JDBC Driver should be fixed since it now uses StringPreparations.SASL_PREPARATION which allows the use of spaces.

**Pull request closed without merging**
