### PR TITLE
chore(deps): Update dependencies

### PR DESCRIPTION
**Pull request by reneleonhardt**
### Updates
* Dependencies, plugins and annotation processors
* [Maven 3.9.7](https://maven.apache.org/docs/3.9.7/release-notes.html) and [Wrapper 3.3.2](https://lists.apache.org/thread/rmv0mknf10y7zj1bvdn4cx5ndblq3rl3)
* GitHub Actions
* Let Dependabot update Maven files and GitHub Actions

### Improvements
* Use dependencyManagement where it makes life easier 😅

### CODE REVIEW

**Comment by jorsol** [comment]
Hi @reneleonhardt I missed your PR, could you please rebase with main (for the pending changes)?

**Comment by reneleonhardt** [comment]
> Hi @reneleonhardt I missed your PR, could you please rebase with main (for the pending changes)?

It happens, done 🙂

**Comment by jorsol** [comment]
Thank you!

**Comment by reneleonhardt** [comment]
You're welcome! 🙂

**Pull request merged**
